/* ============================================
   ÜRETİLMİŞ — kaynak data/games.json (node tools/build-catalog.js). ELLE DÜZENLENMEZ.
   --------------------------------------------
   Hub kataloğu: js/app.js (kayıt defteri), js/hub-ia.js (yaş rafı), js/lock-catalog.js (kilit listesi),
   js/i18n.js (TR.games) ve js/admin.js buradan türetir. Değişiklik data/games.json'a yapılır, sonra `npm run catalog`.
   GAME_SHELVES  : yaş rafları (B2b), görünüm sırasıyla; ages = kapsanan tam yaşlar [ilk, son] (kapalı aralık),
                   yas = görünen etiket. Oyun age aralığı ages ile kesişiyorsa o rafa girer (js/hub-ia.js).
   GAME_SECTIONS : hub bölümleri, görünüm sırasıyla; icon = js/app.js categoryIcons anahtarı,
                   color = css/tokens.css --kat-<id> gelene kadar yedek renk.
   GAME_CATALOG  : 57 kayıt (48 solo + 11 online), hub sırası; about/cat gibi yalnız
                   SEO üreticide (seo/build_seo.py) kullanılan alanlar burada yok.
   GAME_MODULES  : modül adı → tembel referans. Üst düzey const modüller window'a bağlanmaz
                   (window[ad] çalışmaz), eval CSP'yi kırar — tek güvenli yol bu thunk tablosudur.
   Sıra: index.html bu dosyayı js/errors.js'ten hemen sonra, i18n/lock-catalog/app.js'ten önce yükler.
   ============================================ */
/* exported GAME_SHELVES */
const GAME_SHELVES = [
    {"id":"anaokulu","label":"Anaokulu","yas":"4-6","ages":[4,5]},
    {"id":"sinif-1-2","label":"1-2. Sınıf","yas":"6-8","ages":[6,7]},
    {"id":"sinif-3-4","label":"3-4. Sınıf","yas":"8-10","ages":[8,9]},
    {"id":"sinif-5-6","label":"5-6. Sınıf","yas":"10-12","ages":[10,12]},
];
const GAME_SECTIONS = [
    {"id":"harf","title":"Harfler & Kelimeler","icon":"letters","color":"#45B7D1"},
    {"id":"sayi","title":"Sayılar & Matematik","icon":"numbers","color":"#4ECDC4"},
    {"id":"bulmaca","title":"Bulmaca & Mantık","icon":"puzzles","color":"#A55EEA"},
    {"id":"yaratici","title":"Yaratıcılık","icon":"creativity","color":"#FF78C4"},
    {"id":"strateji","title":"Strateji & Macera","icon":"strategy","color":"#27AE60"},
    {"id":"online","title":"Online Çok Oyunculu","icon":"online","color":"#5B4A8A"},
];
const GAME_CATALOG = [
    {"slug":"harf-tanima","name":"Harf Tanıma","module":"HarfTanima","section":"harf","subject":"turkce","age":[4,7],"minutes":5,"levels":3,"teaches":"Harf tanıma ve okuma hazırlığı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/harf-tanima.js"],"css":[]}},
    {"slug":"klavye-kasifi","name":"Klavye Kâşifi","module":"KlavyeKasifi","section":"harf","subject":"turkce","age":[4,6],"minutes":3,"levels":3,"teaches":"Klavye tanıma: harfi tuşta bulma, tek basış, sıra ve Boşluk tuşu","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/klavye-kasifi.js"],"css":["css/klavye-kasifi.css"]}},
    {"slug":"hece-birlestirme","name":"Hece Birleştirme","module":"HeceBirlestirme","section":"harf","subject":"turkce","age":[5,8],"minutes":5,"levels":3,"teaches":"Hece bilgisi ve okuma akıcılığı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/hece-birlestirme.js"],"css":[]}},
    {"slug":"kelime-madeni-3d","name":"Kelime Madeni 3D","module":"KelimeMadeni3D","section":"harf","subject":"ingilizce","age":[8,12],"minutes":15,"levels":1,"teaches":"İngilizce kelime dağarcığı ve mekânsal düşünme","players":"Tek kişilik","players_range":[1,1],"active":false,"stars":0,"files":{"js":["js/games/kelime-madeni-3d.js"],"css":["css/kelime-madeni-3d.css"]}},
    {"slug":"kelime-balonu","name":"Kelime Balonu","module":"KelimeBalonu","section":"harf","subject":"ingilizce","age":[8,12],"minutes":4,"levels":1,"teaches":"İngilizce kelime dağarcığı ve yazım (spelling)","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/kelime-balonu.js"],"css":["css/kelime-balonu.css"]}},
    {"slug":"kelime-canavarlari","name":"Kelime Canavarları","module":"KelimeCanavarlari","section":"harf","subject":"ingilizce","age":[8,12],"minutes":5,"levels":1,"teaches":"İngilizce kelime kategorileri (hayvanlar, yiyecekler, renkler...)","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/kelime-canavarlari.js"],"css":["css/kelime-canavarlari.css"]}},
    {"slug":"kelime-kurtarma","name":"Kelime Kurtarma","module":"KelimeKurtarma","section":"harf","subject":"turkce","age":[6,12],"minutes":3,"levels":1,"teaches":"Türkçe yazım, İngilizce spelling, deyimler","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/kelime-kurtarma.js"],"css":["css/kelime-kurtarma.css"]}},
    {"slug":"gunluk-kelime","name":"Günlük Kelime","module":"GunlukKelime","section":"harf","subject":"turkce","age":[7,12],"minutes":3,"levels":1,"teaches":"Türkçe ve İngilizce yazım, sözcük dağarcığı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/gunluk-kelime.js"],"css":["css/gunluk-kelime.css"]}},
    {"slug":"sayi-sayma","name":"Sayı Sayma","module":"SayiSayma","section":"sayi","subject":"matematik","age":[4,7],"minutes":3,"levels":3,"teaches":"Sayma ve sayı tanıma","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/sayi-sayma.js"],"css":[]}},
    {"slug":"matematik","name":"Matematik","module":"Matematik","section":"sayi","subject":"matematik","age":[5,9],"minutes":3,"levels":3,"teaches":"Toplama, çıkarma ve hızlı işlem","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/matematik.js"],"css":[]}},
    {"slug":"desen","name":"Desen Tamamlama","module":"Desen","section":"sayi","subject":"matematik","age":[5,9],"minutes":3,"levels":3,"teaches":"Örüntü ve mantıksal akıl yürütme","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/desen.js"],"css":[]}},
    {"slug":"bilgi-madencisi","name":"Bilgi Madencisi","module":"BilgiMadencisi","section":"sayi","subject":"matematik","age":[8,12],"minutes":2,"levels":1,"teaches":"Dört işlem akıcılığı, kesirler ve hızlı karar verme","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilgi-madencisi.js"],"css":["css/bilgi-madencisi.css"]}},
    {"slug":"matematik-patlatma","name":"Matematik Patlatma","module":"MatematikPatlatma","section":"sayi","subject":"matematik","age":[8,12],"minutes":2,"levels":1,"teaches":"Zihinden işlem akıcılığı ve sayı hissi","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/matematik-patlatma.js"],"css":["css/matematik-patlatma.css"]}},
    {"slug":"matematik-kafe","name":"Matematik Kafe","module":"MatematikKafe","section":"sayi","subject":"matematik","age":[8,12],"minutes":3,"levels":1,"teaches":"Günlük hayat matematiği: alışveriş, para üstü, oran ve yüzde","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/matematik-kafe.js"],"css":["css/matematik-kafe.css"]}},
    {"slug":"bilgi-yilani","name":"Bilgi Yılanı","module":"BilgiYilani","section":"sayi","subject":"matematik","age":[7,12],"minutes":3,"levels":1,"teaches":"Dört işlem akıcılığı + refleks ve yön planlama","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilgi-yilani.js"],"css":["css/bilgi-yilani.css"]}},
    {"slug":"ritim-sorulari","name":"Ritim Soruları","module":"RitimSorulari","section":"sayi","subject":"matematik","age":[7,12],"minutes":2,"levels":1,"teaches":"Zihinden işlem hızı + dikkat ve ritim","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/ritim-sorulari.js"],"css":["css/ritim-sorulari.css"]}},
    {"slug":"kesir-2048","name":"Kesir 2048","module":"Kesir2048","section":"sayi","subject":"matematik","age":[8,12],"minutes":5,"levels":1,"teaches":"Kesirler, denk kesirler ve birim kesir kavramı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/kesir-2048.js"],"css":["css/kesir-2048.css"]}},
    {"slug":"sayi-ninja","name":"Sayı Ninja","module":"SayiNinja","section":"sayi","subject":"matematik","age":[8,12],"minutes":2,"levels":1,"teaches":"Sayı hissi: çift-tek, katlar, asallık, kare sayılar, kesir karşılaştırma","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/sayi-ninja.js"],"css":["css/sayi-ninja.css"]}},
    {"slug":"hafiza-kartlari","name":"Hafıza Kartları","module":"HafizaKartlari","section":"bulmaca","subject":"genel","age":[4,9],"minutes":3,"levels":10,"teaches":"Görsel hafıza ve dikkat","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/hafiza-kartlari.js"],"css":[]}},
    {"slug":"sekil-bulmaca","name":"Şekil Bulmaca","module":"SekilBulmaca","section":"bulmaca","subject":"matematik","age":[4,8],"minutes":3,"levels":3,"teaches":"Şekil-uzay ilişkisi ve dikkat","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/sekil-bulmaca.js"],"css":[]}},
    {"slug":"siralama","name":"Sıralama","module":"Siralama","section":"bulmaca","subject":"matematik","age":[4,8],"minutes":3,"levels":3,"teaches":"Sıralama ve karşılaştırma mantığı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/siralama.js"],"css":[]}},
    {"slug":"jigsaw","name":"Jigsaw Bulmaca","module":"Jigsaw","section":"bulmaca","subject":"genel","age":[5,10],"minutes":5,"levels":3,"teaches":"Görsel algı ve sabır","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/jigsaw.js"],"css":[]}},
    {"slug":"tetris","name":"Tetris","module":"Tetris","section":"bulmaca","subject":"strateji","age":[6,10],"minutes":5,"levels":1,"teaches":"Mekânsal düşünme ve hızlı planlama","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":10,"files":{"js":["js/games/tetris.js"],"css":["css/tetris.css"]}},
    {"slug":"bilim-dedektifi","name":"Bilim Dedektifi","module":"BilimDedektifi","section":"bulmaca","subject":"fen","age":[8,12],"minutes":3,"levels":1,"teaches":"Fen kavramları, gözlem ve dikkat","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilim-dedektifi.js"],"css":["css/bilim-dedektifi.css"]}},
    {"slug":"eslestirme-ustasi","name":"Eşleştirme Ustası","module":"EslestirmeUstasi","section":"bulmaca","subject":"genel","age":[6,12],"minutes":3,"levels":1,"teaches":"Hafıza + işlem/kelime/fen bilgisi bir arada","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/eslestirme-ustasi.js"],"css":["css/eslestirme-ustasi.css"]}},
    {"slug":"labirent-avcisi","name":"Labirent Avcısı","module":"LabirentAvcisi","section":"bulmaca","subject":"turkce","age":[7,12],"minutes":3,"levels":1,"teaches":"Yazım sırası, planlama ve yön bulma","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/labirent-avcisi.js"],"css":["css/labirent-avcisi.css"]}},
    {"slug":"renk-eslestirme","name":"Renk Eşleştirme","module":"RenkEslestirme","section":"yaratici","subject":"sanat","age":[4,7],"minutes":3,"levels":3,"teaches":"Renk tanıma ve eşleştirme","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/renk-eslestirme.js"],"css":[]}},
    {"slug":"boyama","name":"Boyama","module":"Boyama","section":"yaratici","subject":"sanat","age":[3,8],"minutes":5,"levels":10,"teaches":"Yaratıcılık ve renk bilgisi","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/boyama.js"],"css":[]}},
    {"slug":"tuval","name":"Tuval","module":"Tuval","section":"yaratici","subject":"sanat","age":[5,10],"minutes":10,"levels":3,"teaches":"Piksel sanatı ve yaratıcılık","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/tuval.js"],"css":["css/tuval.css"]}},
    {"slug":"sayilarla-boyama","name":"Sayılarla Boyama","module":"SayilarlaBoyama","section":"yaratici","subject":"sanat","age":[4,9],"minutes":5,"levels":6,"teaches":"Sayı tanıma, dikkat ve ince motor beceri","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/sayilarla-boyama.js"],"css":["css/sayilarla-boyama.css"]}},
    {"slug":"emoji-yapici","name":"Emoji Yapıcı","module":"EmojiYapici","section":"yaratici","subject":"sanat","age":[4,10],"minutes":5,"levels":1,"teaches":"Yaratıcılık ve görsel tasarım","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/emoji-yapici.js"],"css":["css/emoji-yapici.css"]}},
    {"slug":"kod-macerasi","name":"Kod Macerası","module":"KodMacerasi","section":"strateji","subject":"kodlama","age":[6,10],"minutes":5,"levels":3,"teaches":"Algoritma ve kodlama mantığı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"online":{"module":"KodMacerasiMP","order":3,"stars":50,"files":{"js":["js/games/kod-macerasi-shared.js","js/games/kod-macerasi-mp.js"],"css":["css/kod-macerasi.css"]}},"files":{"js":["js/games/kod-macerasi-shared.js","js/games/kod-macerasi.js"],"css":["css/kod-macerasi.css"]}},
    {"slug":"lego-macerasi","name":"LEGO Macerası","module":"LegoMacerasi","section":"strateji","subject":"kodlama","age":[6,10],"minutes":5,"levels":3,"teaches":"Kodlama + inşa becerisi","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/lego-macerasi.js"],"css":["css/kod-macerasi.css"]}},
    {"slug":"lego-world","name":"LEGO World 3D","module":"LegoWorld","section":"strateji","subject":"sanat","age":[6,10],"minutes":15,"levels":9,"teaches":"Mekânsal düşünme ve yaratıcılık","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js","js/lib/GLTFLoader.r128.js","js/games/lego-world.js"],"css":["css/lego-world.css"]}},
    {"slug":"satranc","name":"Satranç","module":"Satranc","section":"strateji","subject":"strateji","age":[6,10],"minutes":15,"levels":1,"teaches":"Strateji, planlama ve mantık","players":"Tek kişilik (AI'ya karşı)","players_range":[1,1],"active":true,"stars":0,"online":{"module":"SatrancMP","order":4,"stars":55,"files":{"js":["js/lib/chess.0.10.3.min.js","js/games/satranc-engine.js","js/games/satranc-mp.js"],"css":["css/satranc.css"]}},"files":{"js":["js/lib/chess.0.10.3.min.js","js/games/satranc-engine.js","js/games/satranc.js"],"css":["css/satranc.css"]}},
    {"slug":"zipla-topla","name":"Zıpla Topla","module":"ZiplaTopla","section":"strateji","subject":"spor","age":[5,10],"minutes":5,"levels":12,"teaches":"Zamanlama, refleks ve koordinasyon","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":15,"files":{"js":["js/games/zipla-topla-levels.js","js/games/zipla-topla.js"],"css":["css/zipla-topla.css"]}},
    {"slug":"space-waves","name":"SpaceWaves","module":"SpaceWaves","section":"strateji","subject":"spor","age":[6,10],"minutes":2,"levels":1,"teaches":"Refleks ve odaklanma","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":20,"files":{"js":["js/games/space-waves-questions.js","js/games/space-waves.js"],"css":["css/space-waves.css"]}},
    {"slug":"egim","name":"Eğim","module":"Egim","section":"strateji","subject":"spor","age":[6,10],"minutes":2,"levels":1,"teaches":"Hızlı refleks ve odak","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":25,"files":{"js":["js/games/egim.js"],"css":["css/egim.css"]}},
    {"slug":"buz-kulesi","name":"Buz Kulesi","module":"BuzKulesi","section":"strateji","subject":"spor","age":[6,10],"minutes":3,"levels":1,"teaches":"Zamanlama, refleks ve denge","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":30,"files":{"js":["js/games/buz-kulesi.js"],"css":["css/buz-kulesi.css"]}},
    {"slug":"penalti","name":"Penaltı","module":"Penalti","section":"strateji","subject":"spor","age":[5,10],"minutes":3,"levels":9,"teaches":"El-göz koordinasyonu ve zamanlama","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":35,"files":{"js":["js/games/penalti.js"],"css":["css/penalti.css"]}},
    {"slug":"zindan-okcusu","name":"Zindan Okçusu","module":"ZindanOkcusu","section":"strateji","subject":"strateji","age":[7,10],"minutes":10,"levels":1,"teaches":"Refleks, strateji ve karar verme","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":40,"files":{"js":["js/games/zindan-okcusu.js"],"css":["css/zindan-okcusu.css"]}},
    {"slug":"bil-ve-fethet","name":"Bil ve Fethet","module":"BilVeFethet","section":"strateji","subject":"genel","age":[8,12],"minutes":15,"levels":1,"teaches":"Genel kültür, strateji ve hızlı karar verme","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bil-ve-fethet.js"],"css":["css/bil-ve-fethet.css"]}},
    {"slug":"bilgi-takimi","name":"Bilgi Takımı","module":"BilgiTakimi","section":"strateji","subject":"genel","age":[8,12],"minutes":5,"levels":1,"teaches":"Matematik, Türkçe, fen ve İngilizce — düzenli çalışma alışkanlığı","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilgi-takimi.js"],"css":["css/bilgi-takimi.css"]}},
    {"slug":"bilgi-ciftligi","name":"Bilgi Çiftliği","module":"BilgiCiftligi","section":"strateji","subject":"genel","age":[8,12],"minutes":5,"levels":1,"teaches":"Tüm dersler + sabır ve planlama","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilgi-ciftligi.js"],"css":["css/bilgi-ciftligi.css"]}},
    {"slug":"bilgi-kulesi","name":"Bilgi Kulesi","module":"BilgiKulesi","section":"strateji","subject":"genel","age":[8,12],"minutes":6,"levels":1,"teaches":"Tüm dersler — strateji ve risk yönetimiyle birlikte","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilgi-kulesi.js"],"css":["css/bilgi-kulesi.css"]}},
    {"slug":"cevap-kosusu","name":"Cevap Koşusu","module":"CevapKosusu","section":"strateji","subject":"genel","age":[7,12],"minutes":3,"levels":1,"teaches":"Tüm dersler + hızlı karar verme ve refleks","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/cevap-kosusu.js"],"css":["css/cevap-kosusu.css"]}},
    {"slug":"bilgi-savunmasi","name":"Bilgi Savunması","module":"BilgiSavunmasi","section":"strateji","subject":"matematik","age":[8,12],"minutes":5,"levels":1,"teaches":"İşlem akıcılığı + kaynak yönetimi ve strateji","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/bilgi-savunmasi.js"],"css":["css/bilgi-savunmasi.css"]}},
    {"slug":"fizik-firlatma","name":"Fizik Fırlatma","module":"FizikFirlatma","section":"strateji","subject":"fen","age":[8,12],"minutes":5,"levels":1,"teaches":"Açı, kuvvet ve yerçekimi — kinestetik fizik öğrenimi","players":"Tek kişilik","players_range":[1,1],"active":true,"stars":0,"files":{"js":["js/games/fizik-firlatma.js"],"css":["css/fizik-firlatma.css"]}},
    {"slug":"kelime-tahmin","name":"Kelime Tahmin","module":null,"section":"online","subject":"turkce","age":[7,10],"minutes":5,"teaches":"Kelime bilgisi ve tümdengelim","players":"Online çok oyunculu","players_range":[2,null],"active":true,"stars":0,"online":{"module":"KelimeTahmin","order":1,"stars":40},"files":{"js":["js/games/kelime-tahmin.js"],"css":[]}},
    {"slug":"harf-tahmin","name":"Harf Tahmin","module":null,"section":"online","subject":"turkce","age":[7,10],"minutes":5,"teaches":"Kelime bilgisi ve tahmin","players":"Online çok oyunculu","players_range":[2,null],"active":true,"stars":0,"online":{"module":"HarfTahmin","order":2,"stars":45},"files":{"js":["js/games/harf-tahmin.js"],"css":[]}},
    {"slug":"penalti-mp","name":"Penaltı Online","module":null,"section":"online","subject":"spor","age":[6,10],"minutes":3,"teaches":"Zamanlama, refleks ve rekabet","players":"Online 2 kişilik","players_range":[2,2],"active":true,"stars":0,"online":{"module":"PenaltiMP","order":5,"stars":60},"files":{"js":["js/games/penalti-mp.js"],"css":["css/penalti.css"]}},
    {"slug":"ates-buz","name":"Ateş & Buz","module":null,"section":"online","subject":"strateji","age":[6,10],"minutes":5,"teaches":"İş birliği ve koordinasyon","players":"2 kişilik / online","players_range":[2,2],"active":true,"stars":0,"online":{"module":"AtesBuz","order":6,"stars":65},"files":{"js":["js/games/ates-buz.js"],"css":["css/ates-buz.css"]}},
    {"slug":"zipla-topla-coop","name":"Zıpla Topla Online","module":null,"section":"online","subject":"spor","age":[6,12],"minutes":5,"teaches":"İş birliği, zamanlama ve koordinasyon","players":"Online 2 kişilik (co-op)","players_range":[2,2],"active":true,"stars":0,"online":{"module":"ZiplaToplaCoop","order":7,"stars":30},"files":{"js":["js/games/zipla-topla-levels.js","js/games/zipla-topla.js"],"css":["css/zipla-topla.css"]}},
    {"slug":"hava-hokeyi","name":"Hava Hokeyi","module":null,"section":"online","subject":"spor","age":[6,12],"minutes":5,"teaches":"Refleks, el-göz koordinasyonu ve açı sezgisi","players":"Online 2 kişilik","players_range":[2,2],"active":true,"stars":0,"online":{"module":"HavaHokeyi","order":8,"stars":75},"files":{"js":["js/games/hava-hokeyi.js"],"css":["css/hava-hokeyi.css"]}},
    {"slug":"altin-avi","name":"Altın Avı","module":null,"section":"online","subject":"genel","age":[7,10],"minutes":5,"teaches":"Genel kültür ve hızlı düşünme","players":"Online (5-30 kişi)","players_range":[5,30],"active":true,"stars":0,"online":{"module":"AltinAvi","order":9,"stars":70},"files":{"js":["js/games/altin-avi-questions.js","js/games/altin-avi.js"],"css":["css/altin-avi.css","css/fonts-altin-avi.css"]}},
    {"slug":"kelimelik","name":"Kelimelik","module":null,"section":"online","subject":"turkce","age":[7,10],"minutes":15,"teaches":"Kelime bilgisi, strateji ve Türkçe yazım","players":"Online 2 kişilik","players_range":[2,2],"active":true,"stars":0,"online":{"module":"Kelimelik","order":10,"stars":0},"files":{"js":["js/games/kelimelik.js"],"css":[]}},
    {"slug":"son-kart","name":"Son Kart","module":null,"section":"online","subject":"strateji","age":[6,12],"minutes":10,"teaches":"Renk-sayı eşleştirme, sıra takibi ve strateji","players":"Tek kişilik (bota karşı) ya da online 2-4 kişi","players_range":[1,4],"active":true,"stars":0,"online":{"module":"SonKart","order":11,"stars":0,"badge":"2-4 Oyuncu"},"files":{"js":["js/games/son-kart.js"],"css":[]}},
];
const GAME_MODULES = {
    HarfTanima: () => HarfTanima,
    KlavyeKasifi: () => KlavyeKasifi,
    HeceBirlestirme: () => HeceBirlestirme,
    KelimeMadeni3D: () => KelimeMadeni3D,
    KelimeBalonu: () => KelimeBalonu,
    KelimeCanavarlari: () => KelimeCanavarlari,
    KelimeKurtarma: () => KelimeKurtarma,
    GunlukKelime: () => GunlukKelime,
    SayiSayma: () => SayiSayma,
    Matematik: () => Matematik,
    Desen: () => Desen,
    BilgiMadencisi: () => BilgiMadencisi,
    MatematikPatlatma: () => MatematikPatlatma,
    MatematikKafe: () => MatematikKafe,
    BilgiYilani: () => BilgiYilani,
    RitimSorulari: () => RitimSorulari,
    Kesir2048: () => Kesir2048,
    SayiNinja: () => SayiNinja,
    HafizaKartlari: () => HafizaKartlari,
    SekilBulmaca: () => SekilBulmaca,
    Siralama: () => Siralama,
    Jigsaw: () => Jigsaw,
    Tetris: () => Tetris,
    BilimDedektifi: () => BilimDedektifi,
    EslestirmeUstasi: () => EslestirmeUstasi,
    LabirentAvcisi: () => LabirentAvcisi,
    RenkEslestirme: () => RenkEslestirme,
    Boyama: () => Boyama,
    Tuval: () => Tuval,
    SayilarlaBoyama: () => SayilarlaBoyama,
    EmojiYapici: () => EmojiYapici,
    KodMacerasi: () => KodMacerasi,
    LegoMacerasi: () => LegoMacerasi,
    LegoWorld: () => LegoWorld,
    Satranc: () => Satranc,
    ZiplaTopla: () => ZiplaTopla,
    SpaceWaves: () => SpaceWaves,
    Egim: () => Egim,
    BuzKulesi: () => BuzKulesi,
    Penalti: () => Penalti,
    ZindanOkcusu: () => ZindanOkcusu,
    BilVeFethet: () => BilVeFethet,
    BilgiTakimi: () => BilgiTakimi,
    BilgiCiftligi: () => BilgiCiftligi,
    BilgiKulesi: () => BilgiKulesi,
    CevapKosusu: () => CevapKosusu,
    BilgiSavunmasi: () => BilgiSavunmasi,
    FizikFirlatma: () => FizikFirlatma,
    KelimeTahmin: () => KelimeTahmin,
    HarfTahmin: () => HarfTahmin,
    KodMacerasiMP: () => KodMacerasiMP,
    SatrancMP: () => SatrancMP,
    PenaltiMP: () => PenaltiMP,
    AtesBuz: () => AtesBuz,
    ZiplaToplaCoop: () => ZiplaToplaCoop,
    HavaHokeyi: () => HavaHokeyi,
    AltinAvi: () => AltinAvi,
    Kelimelik: () => Kelimelik,
    SonKart: () => SonKart,
};
